services:
  # A Docker web service
  - type: web
    name: makelele
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install --no-cache-dir -r requirements.lock
    startCommand: cd src && fastapi run makelele/main.py --host 0.0.0.0 --port $PORT
